# Generated by Django 5.2.5 on 2025-09-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_jobposts_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
