# Generated by Django 5.2.5 on 2025-09-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_application_answers_application_match_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='application',
            name='match_score',
        ),
        migrations.RemoveField(
            model_name='jobposts',
            name='questions',
        ),
    ]
