# Generated by Django 5.2.5 on 2025-09-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_remove_application_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobposts',
            name='questions',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
