# Generated by Django 5.2.5 on 2025-09-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposts',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
