# Generated by Django 5.2.5 on 2025-09-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chats', '0002_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images/'),
        ),
    ]
