# Generated by Django 6.0.2 on 2026-02-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
