# Generated by Django 5.2.5 on 2025-09-14 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_emailotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
